# Disable all non key based authentication
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no

# Enable key authentication
PubkeyAuthentication yes

# Disable direct root login through ssh
PermitRootLogin no
